using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

/// <summary>
/// Builds a scrollable text list of unlocked levels (1..n) and focuses the newest unlocked level.
/// </summary>
public class LevelMenu : MonoBehaviour
{
    private const string LegacyButtonsChildName = "Level Buttons";

    [SerializeField] private int minimumLevels = 20; // Replaced totalLevels
    [SerializeField] private Vector2 cellSize = new Vector2(120f, 120f);
    [SerializeField] private Vector2 gridSpacing = new Vector2(16f, 16f);
    [SerializeField] private float scrollPadding = 16f;
    [SerializeField] private float focusScale = 1.04f;

    [Header("PopUp Layout")]
    [SerializeField] private Vector2 popUpSize = new Vector2(780f, 1250f);
    [SerializeField] private Vector2 popUpPosition = new Vector2(0f, -40f);

    [Header("Scroll Area Layout")]
    [SerializeField] private Vector2 scrollAreaSize = new Vector2(560f, 760f);
    [SerializeField] private Vector2 scrollAreaPosition = new Vector2(0f, -120f);
    [SerializeField] private Color completedColor = Color.white;
    [SerializeField] private Color focusColor = new Color(0.8f, 0.9f, 1f, 1f);
    [SerializeField] private Color lockedColor = new Color(0.4f, 0.4f, 0.4f, 1f);
    [SerializeField] private Color textColor = Color.white;
    [SerializeField] private Sprite buttonSprite;
    [SerializeField] private Sprite lockIconSprite;

    [Header("Back Button Layout")]
    [SerializeField] private Vector2 backButtonPosition = new Vector2(-324f, 705f);
    [SerializeField] private Vector2 backButtonSize = new Vector2(150f, 150f);
    [SerializeField] private Vector2 backButtonAnchor = new Vector2(0.5f, 0.5f);

    private ScrollRect _scrollRect;
    private RectTransform _content;
    private readonly List<Button> _spawnedButtons = new List<Button>();
    private bool _uiBuilt;
    private Coroutine _scrollCoroutine;
    private int _lastBuiltCount;

    [Header("Behavior")]
    [SerializeField] private bool useAutoGeneratedGrid = true;

    private void OnEnable()
    {
        RectTransform rt = GetComponent<RectTransform>();
        if (rt != null)
        {
            rt.anchorMin = Vector2.zero;
            rt.anchorMax = Vector2.one;
            rt.offsetMin = Vector2.zero;
            rt.offsetMax = Vector2.zero;
            rt.anchoredPosition = Vector2.zero;
        }

        Transform popUp = transform.Find("PopUp");
        if (popUp != null)
        {
            RectTransform popUpRt = popUp.GetComponent<RectTransform>();
            if (popUpRt != null)
            {
                popUpPosition = popUpRt.anchoredPosition;
                popUpSize = popUpRt.sizeDelta;
            }
        }

        Transform backBtn = transform.Find("BackButton");
        if (backBtn != null)
        {
            RectTransform backRt = backBtn.GetComponent<RectTransform>();
            if (backRt != null)
            {
                backButtonPosition = backRt.anchoredPosition;
            }
        }

        // Disable SafeArea on parent if present to ensure truly full screen
        SafeArea safeArea = GetComponentInParent<SafeArea>();
        if (safeArea != null)
        {
            safeArea.enabled = false;
            RectTransform saRect = safeArea.GetComponent<RectTransform>();
            saRect.anchorMin = Vector2.zero;
            saRect.anchorMax = Vector2.one;
            saRect.offsetMin = Vector2.zero;
            saRect.offsetMax = Vector2.zero;
        }

        RefreshLevelList();
    }

    private void OnDisable()
    {
        // Re-enable SafeArea when closing this menu so other menus get safe area
        SafeArea safeArea = GetComponentInParent<SafeArea>();
        if (safeArea != null)
        {
            safeArea.enabled = true;
        }
    }

    public void RefreshLevelList()
    {
        if (useAutoGeneratedGrid)
        {
            EnsureScrollUi();
            RebuildLevelButtons();
            ScrollToFocusLevel();
        }
    }

    public void OpenLevel(int levelId)
    {
        if (!LevelProgress.IsLevelUnlocked(levelId))
        {
            return;
        }

        string sceneName = LevelProgress.GetSceneNameForLevel(levelId);
        if (!Application.CanStreamedLevelBeLoaded(sceneName))
        {
            Debug.LogWarning("Level scene not in build settings: " + sceneName);
            return;
        }

        LevelProgress.SetSelectedMenuLevel(levelId);
        if (LevelProgress.IsProceduralMenuLevel(levelId))
        {
            ProceduralSession.MarkFreshRunFromMenu();
        }

        SceneManager.LoadScene(sceneName);
    }

    private void EnsureScrollUi()
    {
        Transform existingScroll = transform.Find("PopUp/Level List");
        if (existingScroll == null) existingScroll = transform.Find("Level List");
        if (existingScroll != null)
        {
            RectTransform sRt = existingScroll.GetComponent<RectTransform>();
            if (sRt != null)
            {
                sRt.anchorMin = new Vector2(0.5f, 0.5f);
                sRt.anchorMax = new Vector2(0.5f, 0.5f);
                sRt.pivot = new Vector2(0.5f, 0.5f);
                sRt.anchoredPosition = scrollAreaPosition;
                sRt.sizeDelta = scrollAreaSize;
            }
        }

        if (_uiBuilt)
        {
            return;
        }

        RemoveLegacyButtons();
        BuildScrollView();
        BuildBackButton();
        _uiBuilt = true;
    }

    private void BuildBackButton()
    {
        Transform existing = transform.Find("BackButton");
        if (existing != null)
        {
            // Bring to front so nothing blocks its clicks
            existing.SetAsLastSibling();

            Button existingBtn = existing.GetComponent<Button>();
            if (existingBtn != null)
            {
                existingBtn.onClick.RemoveListener(CloseMenu);
                existingBtn.onClick.AddListener(CloseMenu);

                // Create or find the ClickZone child object
                Transform clickZone = existing.Find("ClickZone");
                
                Image img = existing.GetComponent<Image>();
                if (img != null)
                {
                    // Remove the old padding trick
                    img.raycastPadding = Vector4.zero;
                    
                    // Only disable the main raycast target if a ClickZone actually exists!
                    // This ensures the button works by default if you haven't made a ClickZone yet.
                    if (clickZone != null)
                    {
                        img.raycastTarget = false;
                    }
                    else
                    {
                        img.raycastTarget = true;
                    }
                }

                if (clickZone != null)
                {
                    // If you created a ClickZone manually in the editor, we make sure it works
                    Image czImg = clickZone.GetComponent<Image>();
                    if (czImg != null)
                    {
                        czImg.raycastTarget = true;
                    }
                }
            }
        }
    }

    private void CloseMenu()
    {
        MainMenu menu = FindFirstObjectByType<MainMenu>();
        if (menu != null)
        {
            menu.CloseLevelSelect();
        }
        else
        {
            gameObject.SetActive(false);
        }
    }

    private void RemoveLegacyButtons()
    {
        Transform legacyRoot = transform.Find(LegacyButtonsChildName);
        if (legacyRoot != null)
        {
            Destroy(legacyRoot.gameObject);
        }
    }

    private void BuildScrollView()
    {
        GameObject scrollRoot = new GameObject("Level List", typeof(RectTransform), typeof(ScrollRect), typeof(Image));
        
        Transform parentTarget = transform.Find("PopUp");
        if (parentTarget == null) parentTarget = transform;
        
        scrollRoot.transform.SetParent(parentTarget, false);

        RectTransform scrollRectTransform = scrollRoot.GetComponent<RectTransform>();
        scrollRectTransform.anchorMin = new Vector2(0.5f, 0.5f);
        scrollRectTransform.anchorMax = new Vector2(0.5f, 0.5f);
        scrollRectTransform.pivot = new Vector2(0.5f, 0.5f);
        scrollRectTransform.sizeDelta = scrollAreaSize;
        scrollRectTransform.anchoredPosition = scrollAreaPosition;

        Image scrollBackground = scrollRoot.GetComponent<Image>();
        scrollBackground.color = new Color(0f, 0f, 0f, 0f);
        scrollBackground.raycastTarget = true;

        _scrollRect = scrollRoot.GetComponent<ScrollRect>();
        _scrollRect.horizontal = false;
        _scrollRect.vertical = true;
        _scrollRect.movementType = ScrollRect.MovementType.Clamped;
        _scrollRect.scrollSensitivity = 30f;

        GameObject viewportObject = new GameObject("Viewport", typeof(RectTransform), typeof(RectMask2D));
        viewportObject.transform.SetParent(scrollRoot.transform, false);
        RectTransform viewportRect = viewportObject.GetComponent<RectTransform>();
        StretchToParent(viewportRect);

        GameObject contentObject = new GameObject("Content", typeof(RectTransform), typeof(GridLayoutGroup), typeof(ContentSizeFitter));
        contentObject.transform.SetParent(viewportObject.transform, false);
        _content = contentObject.GetComponent<RectTransform>();
        _content.anchorMin = new Vector2(0.5f, 1f);
        _content.anchorMax = new Vector2(0.5f, 1f);
        _content.pivot = new Vector2(0.5f, 1f);
        _content.anchoredPosition = Vector2.zero;
        _content.sizeDelta = new Vector2(scrollAreaSize.x, 0f);

        GridLayoutGroup layout = contentObject.GetComponent<GridLayoutGroup>();
        layout.childAlignment = TextAnchor.UpperCenter;
        layout.cellSize = cellSize;
        layout.spacing = gridSpacing;
        layout.padding = new RectOffset(
            Mathf.RoundToInt(scrollPadding),
            Mathf.RoundToInt(scrollPadding),
            Mathf.RoundToInt(scrollPadding),
            Mathf.RoundToInt(scrollPadding));

        ContentSizeFitter fitter = contentObject.GetComponent<ContentSizeFitter>();
        fitter.horizontalFit = ContentSizeFitter.FitMode.Unconstrained;
        fitter.verticalFit = ContentSizeFitter.FitMode.PreferredSize;

        _scrollRect.viewport = viewportRect;
        _scrollRect.content = _content;
    }

    private void RebuildLevelButtons()
    {
        if (_content == null)
        {
            return;
        }

        int unlockedCount = LevelProgress.GetUnlockedLevel();
        int focusLevel = LevelProgress.GetFocusLevel();

        int targetLevels = Mathf.Max(minimumLevels, unlockedCount + 1);
        int remainder = targetLevels % 4;
        if (remainder != 0)
        {
            targetLevels += 4 - remainder;
        }

        if (_lastBuiltCount == unlockedCount && _spawnedButtons.Count == targetLevels)
        {
            ApplyButtonStates(unlockedCount, focusLevel);
            return;
        }

        ClearSpawnedButtons();

        for (int level = 1; level <= targetLevels; level++)
        {
            Button button = CreateLevelRow(level, focusLevel, unlockedCount);
            _spawnedButtons.Add(button);
        }

        _lastBuiltCount = unlockedCount;
    }

    private void ClearSpawnedButtons()
    {
        for (int i = _spawnedButtons.Count - 1; i >= 0; i--)
        {
            if (_spawnedButtons[i] != null)
            {
                Destroy(_spawnedButtons[i].gameObject);
            }
        }

        _spawnedButtons.Clear();
    }

    private Button CreateLevelRow(int levelNumber, int focusLevel, int unlockedCount)
    {
        bool isFocused = levelNumber == focusLevel;
        bool isUnlocked = levelNumber <= unlockedCount;

        GameObject rowObject = new GameObject(
            "Level " + levelNumber,
            typeof(RectTransform),
            typeof(CanvasRenderer),
            typeof(Image),
            typeof(Button));
        rowObject.transform.SetParent(_content, false);

        RectTransform rect = rowObject.GetComponent<RectTransform>();
        rect.sizeDelta = cellSize;
        rect.localScale = isFocused ? Vector3.one * focusScale : Vector3.one;

        Image image = rowObject.GetComponent<Image>();
        image.sprite = buttonSprite;
        image.type = Image.Type.Simple;
        
        if (!isUnlocked)
            image.color = lockedColor;
        else if (isFocused)
            image.color = focusColor;
        else
            image.color = completedColor;
        
        image.raycastTarget = true;

        Button button = rowObject.GetComponent<Button>();
        button.targetGraphic = image;
        button.transition = Selectable.Transition.ColorTint;
        ColorBlock colors = button.colors;
        colors.normalColor = image.color;
        colors.highlightedColor = image.color * 1.1f;
        colors.pressedColor = image.color * 0.85f;
        colors.selectedColor = image.color;
        colors.disabledColor = lockedColor;
        button.colors = colors;
        button.onClick.RemoveAllListeners();
        button.interactable = isUnlocked;

        int capturedLevel = levelNumber;
        button.onClick.AddListener(() => OpenLevel(capturedLevel));

        CreateRowLabel(rowObject.transform, levelNumber, isUnlocked);
        return button;
    }

    private void CreateRowLabel(Transform parent, int levelNumber, bool isUnlocked)
    {
        GameObject labelObject = new GameObject("Label", typeof(RectTransform), typeof(TextMeshProUGUI));
        labelObject.transform.SetParent(parent, false);

        RectTransform labelRect = labelObject.GetComponent<RectTransform>();
        StretchToParent(labelRect);

        TextMeshProUGUI label = labelObject.GetComponent<TextMeshProUGUI>();
        if (TMP_Settings.defaultFontAsset != null)
        {
            label.font = TMP_Settings.defaultFontAsset;
        }

        if (isUnlocked)
        {
            int stars = LevelProgress.GetStars(levelNumber);
            string starDisplay = "";
            for (int i = 0; i < 3; i++)
            {
                starDisplay += i < stars ? "<color=#FFD700>*</color>" : "<color=#888888>*</color>";
            }
            label.text = levelNumber.ToString() + "\n<size=50%>" + starDisplay + "</size>";
            label.color = textColor;
        }
        else
        {
            label.text = levelNumber.ToString();
            label.color = new Color(0.8f, 0.8f, 0.8f, 1f);

            if (lockIconSprite != null)
            {
                GameObject iconObj = new GameObject("LockIcon", typeof(RectTransform), typeof(Image));
                iconObj.transform.SetParent(parent, false);
                RectTransform iconRect = iconObj.GetComponent<RectTransform>();
                iconRect.anchorMin = new Vector2(0.5f, 0.5f);
                iconRect.anchorMax = new Vector2(0.5f, 0.5f);
                iconRect.pivot = new Vector2(0.5f, 0.5f);
                iconRect.anchoredPosition = new Vector2(0f, -20f);
                iconRect.sizeDelta = new Vector2(30f, 30f);
                
                Image iconImg = iconObj.GetComponent<Image>();
                iconImg.sprite = lockIconSprite;
                iconImg.raycastTarget = false;
            }
        }

        label.alignment = TextAlignmentOptions.Center;
        label.fontSize = 44f;
        label.fontStyle = FontStyles.Bold;
        label.lineSpacing = 0f;
        label.raycastTarget = false;
    }

    private void ApplyButtonStates(int unlockedCount, int focusLevel)
    {
        for (int i = 0; i < _spawnedButtons.Count; i++)
        {
            Button button = _spawnedButtons[i];
            if (button == null)
            {
                continue;
            }

            int levelNumber = i + 1;
            bool isFocused = levelNumber == focusLevel;
            bool isUnlocked = levelNumber <= unlockedCount;
            button.interactable = isUnlocked;

            Image image = button.GetComponent<Image>();
            if (image != null)
            {
                if (!isUnlocked)
                    image.color = lockedColor;
                else if (isFocused)
                    image.color = focusColor;
                else
                    image.color = completedColor;
            }

            button.transform.localScale = isFocused ? Vector3.one * focusScale : Vector3.one;
        }
    }

    private void ScrollToFocusLevel()
    {
        if (_scrollCoroutine != null)
        {
            StopCoroutine(_scrollCoroutine);
        }

        _scrollCoroutine = StartCoroutine(ScrollToFocusLevelCoroutine());
    }

    private IEnumerator ScrollToFocusLevelCoroutine()
    {
        yield return null;
        Canvas.ForceUpdateCanvases();
        if (_content != null)
        {
            LayoutRebuilder.ForceRebuildLayoutImmediate(_content);
        }

        if (_scrollRect == null || _spawnedButtons.Count == 0)
        {
            yield break;
        }

        int focusLevel = LevelProgress.GetFocusLevel();
        int focusIndex = Mathf.Clamp(focusLevel - 1, 0, _spawnedButtons.Count - 1);
        Button focusButton = _spawnedButtons[focusIndex];
        if (focusButton == null)
        {
            yield break;
        }

        RectTransform focusRect = focusButton.transform as RectTransform;
        RectTransform viewport = _scrollRect.viewport;
        if (focusRect == null || viewport == null || _content == null)
        {
            yield break;
        }

        float contentHeight = _content.rect.height;
        float viewportHeight = viewport.rect.height;
        if (contentHeight <= viewportHeight)
        {
            _scrollRect.verticalNormalizedPosition = 1f;
            yield break;
        }

        float rowTop = -focusRect.anchoredPosition.y;
        float rowCenter = rowTop + focusRect.rect.height * 0.5f;
        float scrollable = contentHeight - viewportHeight;
        float target = rowCenter - viewportHeight * 0.5f;
        _scrollRect.verticalNormalizedPosition = Mathf.Clamp01(1f - target / scrollable);
        _scrollCoroutine = null;
    }

    private static void StretchToParent(RectTransform rect)
    {
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
        rect.pivot = new Vector2(0.5f, 0.5f);
    }
}
